# Generated by Django 4.2.1 on 2023-06-02 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='stock',
            field=models.DecimalField(decimal_places=0, default=10, max_digits=10, verbose_name='stock'),
            preserve_default=False,
        ),
    ]
